#!/usr/bin/awk -f

function ttlesc(str)
{
	gsub(/\\/, "\\\\", str);
	gsub(/"/, "\\\"", str);
	return str;
}

BEGIN {
	FS = "\t";
	OFS = " ";
	print "@prefix foaf: <http://xmlns.com/foaf/0.1/> .";
	print "@prefix figi-gii: <http://www.omg.org/spec/FIGI/GlobalInstrumentIdentifiers/> .";
	print "@prefix owl: <http://www.w3.org/2002/07/owl#> .";
	print "@prefix mic: <http://fadyart.com/markets#> .";
	print "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .";
	print "@prefix gas: <http://schema.ga-group.nl/symbology#> .";
	print "@prefix gn: <http://www.geonames.org/ontology#> .";
	print "@prefix dbo: <http://dbpedia.org/ontology/> .";
	print "@prefix dc: <http://purl.org/dc/elements/1.1/> .";
	print "@prefix time: <http://www.w3.org/2006/time#> .";
	print;

	M["JANUARY"] = "01";
	M["FEBRUARY"] = "02";
	M["MARCH"] = "03";
	M["APRIL"] = "04";
	M["MAY"] = "05";
	M["JUNE"] = "06";
	M["JULY"] = "07";
	M["AUGUST"] = "08";
	M["SEPTEMBER"] = "09";
	M["OCTOBER"] = "10";
	M["NOVEMBER"] = "11";
	M["DECEMBER"] = "12";

	TZ["ABIDJAN"] = "Africa/Abidjan";
	TZ["ABU DHABI"] = "Asia/Dubai";
	TZ["ACCRA"] = "Africa/Accra";
	TZ["AHMEDABAD"] = "Asia/Kolkata";
	TZ["ALGIERS"] = "Africa/Algiers";
	TZ["ALMA-ATA"] = "Asia/Almaty";
	TZ["ALMATY"] = "Asia/Almaty";
	TZ["AMMAN"] = "Asia/Amman";
	TZ["AMSTERDAM"] = "Europe/Amsterdam";
	TZ["ANTANANARIVO"] = "Indian/Antananarivo";
	TZ["ASUNCION"] = "America/Asuncion";
	TZ["ATHENS"] = "Europe/Athens";
	TZ["ATLANTA"] = "America/New_York";
	TZ["AUCKLAND"] = "Pacific/Auckland";
	TZ["AYLESBURY"] = "Europe/London";
	TZ["BAGHDAD"] = "Asia/Baghdad";
	TZ["BAKU"] = "Asia/Baku";
	TZ["BANGALORE"] = "Asia/Kolkata";
	TZ["BANGKOK"] = "Asia/Bangkok";
	TZ["BANJA LUKA"] = "Europe/Sarajevo";
	TZ["BARCELONA"] = "Europe/Madrid";
	TZ["BASSETERRE"] = "America/St_Kitts";
	TZ["BEIRUT"] = "Asia/Beirut";
	TZ["BELGRADE"] = "Europe/Belgrade";
	TZ["BERGEN"] = "Europe/Oslo";
	TZ["BERLIN"] = "Europe/Berlin";
	TZ["BERN"] = "Europe/Zurich";
	TZ["BERNE"] = "Europe/Zurich";
	TZ["BILBAO"] = "Europe/Madrid";
	TZ["BISHKEK"] = "Asia/Bishkek";
	TZ["BLANTYRE"] = "Africa/Blantyre";
	TZ["BOGOTA"] = "America/Bogota";
	TZ["BOSTON"] = "America/New_York";
	TZ["BRATISLAVA"] = "Europe/Bratislava";
	TZ["BRIDGETOWN"] = "America/Barbados";
	TZ["BRUSSELS"] = "Europe/Brussels";
	TZ["BUCHAREST"] = "Europe/Bucharest";
	TZ["BUDAPEST"] = "Europe/Budapest";
	TZ["BUENOS AIRES"] = "America/Argentina/Buenos_Aires";
	TZ["CAIRO"] = "Africa/Cairo";
	TZ["CALCUTTA"] = "Asia/Kolkata";
	TZ["CALGARY"] = "America/Edmonton";
	TZ["CARACAS"] = "America/Caracas";
	TZ["CASABLANCA"] = "Africa/Casablanca";
	TZ["CHICAGO"] = "America/Chicago";
	TZ["CHISINAU"] = "Europe/Chisinau";
	TZ["CHITTAGONG"] = "Asia/Dhaka";
	TZ["COLOMBO"] = "Asia/Colombo";
	TZ["COPENHAGEN"] = "Europe/Copenhagen";
	TZ["CORDOBA"] = "America/Argentina/Cordoba";
	TZ["CORRIENTES"] = "America/Argentina/Cordoba";
	TZ["DALIAN"] = "Asia/Shanghai";
	TZ["DAMASCUS"] = "Asia/Damascus";
	TZ["DAR ES SALAAM"] = "Africa/Dar_es_Salaam";
	TZ["DELHI"] = "Asia/Kolkata";
	TZ["DHAKA"] = "Asia/Dhaka";
	TZ["DNIPROPETROVSK"] = "Europe/Kiev";
	TZ["DOHA"] = "Asia/Qatar";
	TZ["DOUALA"] = "Africa/Douala";
	TZ["DUBAI"] = "Asia/Dubai";
	TZ["DUBLIN"] = "Europe/Dublin";
	TZ["DUESSELDORF"] = "Europe/Berlin";
	TZ["EBENE"] = "Indian/Mauritius";
	TZ["EBENE CITY"] = "Indian/Mauritius";
	TZ["EDEN ISLAND"] = "Indian/Mahe";
	TZ["EL SALVADOR"] = "America/El_Salvador";
	TZ["ESPIRITO SANTO"] = "America/Sao_Paulo";
	TZ["FOSTER CITY"] = "America/Los_Angeles";
	TZ["FRANKFURT"] = "Europe/Berlin";
	TZ["FUKUOKA"] = "Asia/Tokyo";
	TZ["GABORONE"] = "Africa/Gaborone";
	TZ["GEORGETOWN"] = "America/Guyana";
	TZ["GLENVIEW"] = "America/Chicago";
	TZ["GREENWICH"] = "America/New_York";
	TZ["GUATEMALA"] = "America/Guatemala";
	TZ["GUAYAQUIL"] = "America/Guayaquil";
	TZ["GUAYNABO"] = "America/New_York";
	TZ["HAMBURG"] = "Europe/Berlin";
	TZ["HAMILTON"] = "Atlantic/Bermuda";
	TZ["HANNOVER"] = "Europe/Berlin";
	TZ["HANOI"] = "Asia/Ho_Chi_Minh";
	TZ["HARARE"] = "Africa/Harare";
	TZ["HELSINKI"] = "Europe/Helsinki";
	TZ["HO CHI MINH CITY"] = "Asia/Ho_Chi_Minh";
	TZ["HONG KONG"] = "Asia/Hong_Kong";
	TZ["HONG-KONG"] = "Asia/Hong_Kong";
	TZ["HORSENS"] = "Europe/Copenhagen";
	TZ["ILLINOIS"] = "America/Chicago";
	TZ["INDORE MADHYA PRADESH"] = "Asia/Kolkata";
	TZ["ISTANBUL"] = "Europe/Istanbul";
	TZ["JAKARTA"] = "Asia/Jakarta";
	TZ["JERSEY CITY"] = "America/New_York";
	TZ["JOHANNESBURG"] = "Africa/Johannesburg";
	TZ["KAMPALA"] = "Africa/Kampala";
	TZ["KANSAS CITY"] = "America/Chicago";
	TZ["KARACHI"] = "Asia/Karachi";
	TZ["KATHMANDU"] = "Asia/Kathmandu";
	TZ["KHARKOV"] = "Europe/Kiev";
	TZ["KHARTOUM"] = "Africa/Khartoum";
	TZ["KIEV"] = "Europe/Kiev";
	TZ["KIGALI"] = "Africa/Kigali";
	TZ["KINGSTON"] = "America/Jamaica";
	TZ["KONGSVINGER"] = "Europe/Oslo";
	TZ["KUALA LUMPUR"] = "Asia/Kuala_Lumpur";
	TZ["KUWAIT"] = "Asia/Kuwait";
	TZ["LA PAZ"] = "America/La_Paz";
	TZ["LABUAN"] = "Asia/Kuala_Lumpur";
	TZ["LAGOS"] = "Africa/Lagos";
	TZ["LANE COVE"] = "Australia/Sydney";
	TZ["LAO"] = "Asia/Vientiane";
	TZ["LEIPZIG"] = "Europe/Berlin";
	TZ["LENEXA"] = "America/New_York";
	TZ["LIMA"] = "America/Lima";
	TZ["LISBOA"] = "Europe/Lisbon";
	TZ["LISBON"] = "Europe/Lisbon";
	TZ["LJUBLJANA"] = "Europe/Ljubljana";
	TZ["LONDON"] = "Europe/London";
	TZ["LUSAKA"] = "Africa/Lusaka";
	TZ["LUXEMBOURG"] = "Europe/Luxembourg";
	TZ["MADRAS"] = "Asia/Kolkata";
	TZ["MADRID"] = "Europe/Madrid";
	TZ["MAKATI CITY"] = "Asia/Manila";
	TZ["MALE"] = "Indian/Maldives";
	TZ["MANAGUA"] = "America/Managua";
	TZ["MANAMA"] = "Asia/Bahrain";
	TZ["MARINGA"] = "America/Sao_Paulo";
	TZ["MBABANE"] = "Africa/Mbabane";
	TZ["MELBOURNE"] = "Australia/Sydney";
	TZ["MENDOZA"] = "America/Argentina/Mendoza";
	TZ["MEXICO"] = "America/Mexico_City";
	TZ["MILAN"] = "Europe/Rome";
	TZ["MILANO"] = "Europe/Rome";
	TZ["MINNEAPOLIS"] = "America/Chicago";
	TZ["MINSK"] = "Europe/Minsk";
	TZ["MONTENEGRO"] = "Europe/Podgorica";
	TZ["MONTEVIDEO"] = "America/Montevideo";
	TZ["MONTREAL"] = "America/Montreal";
	TZ["MOSCOW"] = "Europe/Moscow";
	TZ["MUENCHEN"] = "Europe/Berlin";
	TZ["MUMBAI"] = "Asia/Kolkata";
	TZ["MUSCAT"] = "Asia/Muscat";
	TZ["NABLUS"] = "Asia/Gaza";
	TZ["NAGOYA"] = "Asia/Tokyo";
	TZ["NAIROBI"] = "Africa/Nairobi";
	TZ["NARBERTH"] = "America/New_York";
	TZ["NASAU"] = "America/Nassau";
	TZ["NEW JERSEY"] = "America/New_York";
	TZ["NEW YORK"] = "America/New_York";
	TZ["NEWCASTLE"] = "Australia/Sydney";
	TZ["NICOSIA"] = "Asia/Nicosia";
	TZ["NICOSIA (LEFKOSIA)"] = "Asia/Nicosia";
	TZ["NOVOSIBIRSK"] = "Asia/Novosibirsk";
	TZ["ODESSA"] = "Europe/Kiev";
	TZ["OSAKA"] = "Asia/Tokyo";
	TZ["OSLO"] = "Europe/Oslo";
	TZ["PANAMA"] = "America/Panama";
	TZ["PARIS"] = "Europe/Paris";
	TZ["PASIG CITY"] = "Asia/Manila";
	TZ["PHILADELPHIA"] = "America/New_York";
	TZ["PHNOM PENH"] = "Asia/Phnom_Penh";
	TZ["PORT LOUIS"] = "Indian/Mauritius";
	TZ["PORT MORESBY"] = "Pacific/Port_Moresby";
	TZ["PORT OF SPAIN"] = "America/Port_of_Spain";
	TZ["PRAGUE"] = "Europe/Prague";
	TZ["PRAIA"] = "Atlantic/Cape_Verde";
	TZ["PRINCETON"] = "America/New_York";
	TZ["QUITO"] = "America/Guayaquil";
	TZ["REYKJAVIK"] = "Atlantic/Reykjavik";
	TZ["RIGA"] = "Europe/Riga";
	TZ["RIO DE JANEIRO"] = "America/Sao_Paulo";
	TZ["RIYADH"] = "Asia/Riyadh";
	TZ["ROMA"] = "Europe/Rome";
	TZ["ROSARIO"] = "America/Argentina/Cordoba";
	TZ["S-HERTOGENBOSCH"] = "Europe/Amsterdam";
	TZ["SAINT-PETERSBURG"] = "Europe/Moscow";
	TZ["SAMARA"] = "Europe/Samara";
	TZ["SAN JOSE"] = "America/Costa_Rica";
	TZ["SANTA FE"] = "America/Argentina/Cordoba";
	TZ["SANTIAGO"] = "America/Santiago";
	TZ["SANTO DOMINGO"] = "America/Santo_Domingo";
	TZ["SAO PAULO"] = "America/Sao_Paulo";
	TZ["SAPPORO"] = "Asia/Tokyo";
	TZ["SARAJEVO"] = "Europe/Sarajevo";
	TZ["SEOUL"] = "Asia/Seoul";
	TZ["SHANGHAI"] = "Asia/Shanghai";
	TZ["SHENZHEN"] = "Asia/Shanghai";
	TZ["SIBIU"] = "Europe/Bucharest";
	TZ["SINGAPORE"] = "Asia/Singapore";
	TZ["SKOPJE"] = "Europe/Skopje";
	TZ["SOFIA"] = "Europe/Sofia";
	TZ["ST.  PETER PORT"] = "Europe/Guernsey";
	TZ["STOCKHOLM"] = "Europe/Stockholm";
	TZ["STUTTGART"] = "Europe/Berlin";
	TZ["SUVA"] = "Pacific/Fiji";
	TZ["SYDNEY"] = "Australia/Sydney";
	TZ["TAIPEI"] = "Asia/Taipei";
	TZ["TALLINN"] = "Europe/Tallinn";
	TZ["TASHKENT"] = "Asia/Tashkent";
	TZ["TBILISI"] = "Asia/Tbilisi";
	TZ["TEGUCIGALPA"] = "America/Tegucigalpa";
	TZ["TEHRAN"] = "Asia/Tehran";
	TZ["TEL AVIV"] = "Asia/Tel_Aviv";
	TZ["TIRANA"] = "Europe/Tirane";
	TZ["TOKYO"] = "Asia/Tokyo";
	TZ["TORONTO"] = "America/Toronto";
	TZ["TORSHAVN"] = "Atlantic/Faroe";
	TZ["TRIPOLI"] = "Africa/Tripoli";
	TZ["TROMSO"] = "Europe/Oslo";
	TZ["TRONDHEIM"] = "Europe/Oslo";
	TZ["TUCUMAN"] = "America/Argentina/Tucuman";
	TZ["TUNIS"] = "Africa/Tunis";
	TZ["ULAAN BAATAR"] = "Asia/Ulaanbaatar";
	TZ["UTRECHT"] = "Europe/Amsterdam";
	TZ["VALENCIA"] = "Europe/Madrid";
	TZ["VALLETTA"] = "Europe/Malta";
	TZ["VALPARAISO"] = "America/Santiago";
	TZ["VANCOUVER"] = "America/Vancouver";
	TZ["VIENNA"] = "Europe/Vienna";
	TZ["VILA"] = "Pacific/Efate";
	TZ["VILNIUS"] = "Europe/Vilnius";
	TZ["WARSAW"] = "Europe/Warsaw";
	TZ["WASHINGTON"] = "America/New_York";
	TZ["WASHINGTON/NEW YORK"] = "America/New_York";
	TZ["WELLINGTON"] = "Pacific/Auckland";
	TZ["WILLEMSTAD"] = "America/Curacao";
	TZ["WINDHOEK"] = "Africa/Windhoek";
	TZ["WINNIPEG"] = "America/Winnipeg";
	TZ["WUXI"] = "Asia/Shanghai";
	TZ["YEREVAN"] = "Asia/Yerevan";
	TZ["ZAGREB"] = "Europe/Zagreb";
	TZ["ZHENGZHOU"] = "Asia/Shanghai";
	TZ["ZURICH"] = "Europe/Zurich";
}
(FNR > 1) {
	print "mic:" $1, "a", "figi-gii:PricingSource ;";
	print "  ", "gn:countryCode", "\"" $3 "\"", ";"
	if ($4 != $1) {
		print "  ", "dbo:operatedBy", "mic:" $4, ";";
	}
	if ($9 && !($9 ~ / /) && $9 ~ /\./) {
		if (tolower(substr($9, 1, 4)) != "http") {
			$9 = "http://" $9;
		}
		print "  ", "foaf:homepage", "<" tolower($9) ">", ";";
	}
	## prepare creation date
	split($12, crea, " ");
	if (M[crea[1]]) {
		print "  ", "dc:created", "\"" crea[2] "-" M[crea[1]] "\"^^xsd:gYearMonth", ";";
	}
	print "  ", "foaf:name", "\"" ttlesc($6) "\"", ";";
	if (TZ[$8]) {
		print "  ", "time:timeZone", "<http://dbpedia.org/resource/" TZ[$8] ">", ";";
	}
	print "  ", "gas:symbolOf", "<http://www.iso20022.org/10383/>", ".";
}
